requirements: Fix broken crc32 update
The package updated from 1.1.2 to 1.1.3 and no longer builds under
alpine due to:

 src/google_crc32c/_crc32c.c:3:10: fatal error: crc32c/crc32c.h: No such file or directory

this pins down to what works

Signed-off-by: Andy Doan <andy@foundries.io>